# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv_store.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kv_store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv_store.proto\x12\x07kvstore\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xae\x01\n\rKeyValueStore\x12\x30\n\x03Set\x12\x13.kvstore.SetRequest\x1a\x14.kvstore.SetResponse\x12\x30\n\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\x12\x39\n\x06\x44\x65lete\x12\x16.kvstore.DeleteRequest\x1a\x17.kvstore.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETREQUEST']._serialized_start=27
  _globals['_SETREQUEST']._serialized_end=67
  _globals['_SETRESPONSE']._serialized_start=69
  _globals['_SETRESPONSE']._serialized_end=99
  _globals['_GETREQUEST']._serialized_start=101
  _globals['_GETREQUEST']._serialized_end=126
  _globals['_GETRESPONSE']._serialized_start=128
  _globals['_GETRESPONSE']._serialized_end=171
  _globals['_DELETEREQUEST']._serialized_start=173
  _globals['_DELETEREQUEST']._serialized_end=201
  _globals['_DELETERESPONSE']._serialized_start=203
  _globals['_DELETERESPONSE']._serialized_end=236
  _globals['_KEYVALUESTORE']._serialized_start=239
  _globals['_KEYVALUESTORE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
